CREATE TABLE Wordle(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    date DATE NOT NULL,
    score VARCHAR(1) NOT NULL
);
CREATE TABLE WordleSummary(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    year INTEGER NOT NULL,
    score VARCHAR(1) NOT NULL,
    count INTEGER NOT NULL
);
CREATE TABLE Colorfle(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    date DATE NOT NULL,
    mode VARCHAR(255) NOT NULL,
    score VARCHAR(1) NOT NULL,
    accuracy DECIMAL(8, 2) NOT NULL
);
CREATE TABLE ColorfleSummary(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    year INTEGER NOT NULL,
    mode VARCHAR(255) NOT NULL,
    score VARCHAR(1) NOT NULL,
    count INTEGER NOT NULL,
    accuracy DECIMAL(8, 2) NOT NULL
);
CREATE TABLE Angle(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    date DATE NOT NULL,
    score VARCHAR(1) NOT NULL,
    dist INTEGER NULL
);
CREATE TABLE AngleSummary(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    year INTEGER NOT NULL,
    score VARCHAR(1) NOT NULL,
    count INTEGER NOT NULL,
    dist INTEGER NULL
);
CREATE TABLE Connections(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    date DATE NOT NULL,
    yellow BOOLEAN NOT NULL,
    green BOOLEAN NOT NULL,
    blue BOOLEAN NOT NULL,
    purple BOOLEAN NOT NULL
);
CREATE TABLE ConnectionSummary(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    year INTEGER NOT NULL,
    yellow INTEGER NOT NULL,
    green INTEGER NOT NULL,
    blue INTEGER NOT NULL,
    purple INTEGER NOT NULL,
    count INTEGER NOT NULL
);
CREATE TABLE Pips(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    date DATE NOT NULL,
    mode VARCHAR(255) NOT NULL,
    time TIME(0) WITHOUT TIME ZONE NOT NULL,
    cookie BOOLEAN NOT NULL
);
CREATE TABLE PipSummary(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userId BIGINT NOT NULL,
    month SMALLINT NOT NULL,
    year INTEGER NOT NULL,
    mode VARCHAR(255) NOT NULL,
    time TIME(0) WITHOUT TIME ZONE NOT NULL,
    cookies INTEGER NOT NULL
);